# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Velodrome_v2
description: Multi-chain indexer for Velodrome V2 on Optimism and Aerodrome on Base
rollback_on_reorg: true
raw_events: false
field_selection:
  transaction_fields:
    - "hash"
contracts:
  - name: FactoryRegistry
    abi_file_path: abis/FactoryRegistry.json
    handler: src/EventHandlers/FactoryRegistry.ts
    events:
      - event: Approve
      - event: Unapprove
  - name: PoolFactory
    abi_file_path: abis/PoolFactory.json
    handler: src/EventHandlers/PoolFactory.ts
    events:
      - event: PoolCreated
      - event: SetCustomFee
  - name: RootCLPoolFactory
    abi_file_path: abis/RootCLPoolFactory.json
    handler: src/EventHandlers/RootCLPoolFactory.ts
    events:
      - event: RootPoolCreated
  - name: CLFactory
    abi_file_path: abis/CLFactory.json
    handler: src/EventHandlers/CLFactory.ts
    events:
      - event: PoolCreated
      - event: TickSpacingEnabled
  - name: CLPool
    abi_file_path: abis/CLPool.json
    handler: src/EventHandlers/CLPool.ts
    events:
      - event: Burn
      - event: Collect
      - event: CollectFees
      - event: Flash
      - event: IncreaseObservationCardinalityNext
      - event: Mint
      - event: SetFeeProtocol
      - event: Swap
  - name: NFPM
    abi_file_path: abis/NFPM.json
    handler: src/EventHandlers/NFPM/NFPM.ts
    events:
      - event: Transfer
      - event: IncreaseLiquidity
      - event: DecreaseLiquidity
  - name: VeNFT
    abi_file_path: abis/VeNFT.json
    handler: src/EventHandlers/VeNFT/VeNFT.ts
    events:
      - event: Deposit
      - event: DepositManaged
      - event: Merge
      - event: Split
      - event: WithdrawManaged
      - event: Withdraw
      - event: Transfer
  - name: Pool
    abi_file_path: abis/Pool.json
    handler: src/EventHandlers/Pool.ts
    events:
      - event: Mint
      - event: Burn
      - event: Fees
      - event: Claim
      - event: Swap
      - event: Sync
      - event: Transfer
  - name: Voter
    abi_file_path: abis/VoterV2.json
    handler: src/EventHandlers/Voter/Voter.ts
    events:
      - event: Voted
      - event: Abstained
      - event: DistributeReward
      - event: GaugeCreated
      - event: GaugeKilled
      - event: GaugeRevived
      - event: WhitelistToken
  - name: SuperchainLeafVoter
    abi_file_path: abis/SuperchainLeafVoter.json
    handler: src/EventHandlers/Voter/SuperchainLeafVoter.ts
    events:
      - event: GaugeCreated
      - event: GaugeKilled
      - event: GaugeRevived
      - event: WhitelistToken
  - name: FeesVotingReward
    abi_file_path: abis/FeesVotingReward.json
    handler: src/EventHandlers/VotingReward/FeesVotingReward.ts
    events:
      - event: ClaimRewards
  - name: BribesVotingReward
    abi_file_path: abis/BribesVotingReward.json
    handler: src/EventHandlers/VotingReward/BribesVotingReward.ts
    events:
      - event: ClaimRewards
  - name: SuperchainIncentiveVotingReward
    abi_file_path: abis/SuperchainIncentiveVotingReward.json
    handler: src/EventHandlers/VotingReward/SuperchainIncentiveVotingReward.ts
    events:
      - event: ClaimRewards
  - name: NewCLGaugeFactory
    abi_file_path: abis/NewCLGaugeFactory.json
    handler: src/EventHandlers/CLGaugeFactory/NewCLGaugeFactory.ts
    events:
      - event: SetDefaultCap
      - event: SetEmissionCap
  - name: CLGauge
    abi_file_path: abis/CLGauge.json
    handler: src/EventHandlers/Gauges/CLGauge.ts
    events:
      - event: Deposit
      - event: Withdraw
      - event: ClaimRewards
  - name: Gauge
    abi_file_path: abis/Gauge.json
    handler: src/EventHandlers/Gauges/Gauge.ts
    events:
      - event: Deposit
      - event: Withdraw
      - event: ClaimRewards
  - name: ALMDeployFactoryV2
    abi_file_path: abis/ALM/DeployFactoryV2.json
    handler: src/EventHandlers/ALM/DeployFactoryV2.ts
    events:
      - event: StrategyCreated
  - name: ALMDeployFactoryV1
    abi_file_path: abis/ALM/DeployFactoryV1.json
    handler: src/EventHandlers/ALM/DeployFactoryV1.ts
    events:
      - event: StrategyCreated
  - name: ALMCore
    abi_file_path: abis/ALM/Core.json
    handler: src/EventHandlers/ALM/Core.ts
    events:
      - event: Rebalance
  - name: ALMLPWrapperV2
    abi_file_path: abis/ALM/LPWrapperV2.json
    handler: src/EventHandlers/ALM/LPWrapperV2.ts
    events:
      - event: Deposit
      - event: Withdraw
      - event: Transfer
      - event: TotalSupplyLimitUpdated
  - name: ALMLPWrapperV1
    abi_file_path: abis/ALM/LPWrapperV1.json
    handler: src/EventHandlers/ALM/LPWrapperV1.ts
    events:
      - event: Deposit
      - event: Withdraw
      - event: Transfer
  - name: DynamicSwapFeeModule
    abi_file_path: abis/DynamicSwapFeeModule.json
    handler: src/EventHandlers/SwapFeeModule/DynamicSwapFeeModule.ts
    events:
      - event: CustomFeeSet
      - event: SecondsAgoSet
      - event: ScalingFactorSet
      - event: FeeCapSet
  - name: CustomSwapFeeModule
    abi_file_path: abis/CustomSwapFeeModule.json
    handler: src/EventHandlers/SwapFeeModule/CustomSwapFeeModule.ts
    events:
      - event: SetCustomFee
  - name: CLPoolLauncher
    handler: src/EventHandlers/PoolLauncher/CLPoolLauncher.ts
    abi_file_path: abis/CLPoolLauncher.json
    events:
      - event: Launch
      - event: Migrate
      - event: EmergingFlagged
      - event: EmergingUnflagged
      - event: PairableTokenAdded
      - event: PairableTokenRemoved
      - event: NewPoolLauncherSet
      - event: CreationTimestampSet
  - name: V2PoolLauncher
    handler: src/EventHandlers/PoolLauncher/V2PoolLauncher.ts
    abi_file_path: abis/V2PoolLauncher.json
    events:
      - event: Launch
      - event: Migrate
      - event: EmergingFlagged
      - event: EmergingUnflagged
      - event: PairableTokenAdded
      - event: PairableTokenRemoved
      - event: NewPoolLauncherSet
      - event: CreationTimestampSet
  - name: VelodromeUniversalRouter
    handler: src/EventHandlers/SuperswapsHyperlane/VelodromeUniversalRouter.ts
    abi_file_path: abis/VelodromeUniversalRouter.json
    events:
      - event: UniversalRouterBridge
      - event: CrossChainSwap
  - name: Mailbox
    handler: src/EventHandlers/SuperswapsHyperlane/Mailbox.ts
    abi_file_path: abis/Mailbox.json
    events:
      - event: DispatchId
      - event: ProcessId
chains:
  - id: 8453 # Base
    start_block: 0
    contracts:
      - name: DynamicSwapFeeModule
        address:
          - 0xDB45818A6db280ecfeB33cbeBd445423d0216b5D
          - 0x00cB12a1c84dfC1b9c70734C0385E769Bc86e9Ef
      - name: CustomSwapFeeModule
        address:
          - 0xF4171B0953b52Fa55462E4d76ecA1845Db69af00
      - name: VeNFT
        address:
          - 0xeBf418Fe2512e7E6bd9b87a8F0f294aCDC67e6B4
      - name: NFPM
        address:
          - 0x827922686190790b37229fd06084350E74485b72
          - 0xa990C6a764b73BF43cee5Bb40339c3322FB9D55F
      - name: FactoryRegistry
        address:
          - 0x5C3F18F06CC09CA1910767A34a20F771039E37C0
      - name: PoolFactory
        address:
          - 0x420DD381b31aEf6683db6B902084cB0FFECe40Da
      - name: CLFactory
        address:
          - 0x5e7BB104d84c7CB9B682AaC2F3d509f5F406809A
          - 0xaDe65c38CD4849aDBA595a4323a8C7DdfE89716a # New CL Factory
          - 0x9592CD9B267748cbfBDe90Ac9F7DF3c437A6d51B # Another CL - abi is slightly different but has no impact on event handlers currently
      - name: NewCLGaugeFactory
        address:
          - 0xB630227a79707D517320b6c0f885806389dFcbB3
      - name: Pool
        address:
      - name: Voter
        address:
          - 0x16613524e02ad97eDfeF371bC883F2F5d6C480A5
      - name: FeesVotingReward
        address:
      - name: BribesVotingReward
        address:
      - name: CLPool
        address:
      - name: ALMDeployFactoryV1
        address:
          - 0x5B1b1aaC71bDca9Ed1dCb2AA357f678584db4029
      - name: ALMDeployFactoryV2
        address:
          - 0xE46EC96906fc6dEC53De25F013639969Fe10180d
      - name: ALMCore
        address:
          - 0x0000000cE42D4981513060aB7E50B9e5e2D19AF1
          - 0xd17613D91150a2345eCe9598D055C7197A1f5A71
      - name: ALMLPWrapperV1
        address:
      - name: ALMLPWrapperV2
        address:
      - name: CLGauge
        address:
      - name: Gauge
        address:
      - name: CLPoolLauncher
        address:
          - 0x122FD2369b86C7d6C848c842a70c0d04A7c6fb84
          - 0xb9A1094D614c70B94C2CD7b4efc3A6adC6e6F4d3
      - name: V2PoolLauncher
        address:
          - 0x8B8025D4cD620BB89e196D32851d4c6E5B74AA60
          - 0xA81eEbdEb3129bf5B89AEd89EDe9eC5fB6FDE3B3
      - name: VelodromeUniversalRouter
        address:
          - 0x01D40099fCD87C018969B0e8D4aB1633Fb34763C
          - 0xa9606caaC711Ac816E568356187EC7a009500Eb2
      - name: Mailbox
        address:
          - 0xeA87ae93Fa0019a82A727bfd3eBd1cFCa8f64f1D