# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: Velodrome_v2
description: Multi-chain indexer for Velodrome V2 on Optimism and Aerodrome on Base
rollback_on_reorg: true
raw_events: false
field_selection:
  transaction_fields:
    - "hash"
contracts:
  - name: FactoryRegistry
    abi_file_path: abis/FactoryRegistry.json
    handler: src/EventHandlers/FactoryRegistry.ts
    events:
      - event: Approve
      - event: Unapprove
  - name: PoolFactory
    abi_file_path: abis/PoolFactory.json
    handler: src/EventHandlers/PoolFactory.ts
    events:
      - event: PoolCreated
      - event: SetCustomFee
  - name: RootCLPoolFactory
    abi_file_path: abis/RootCLPoolFactory.json
    handler: src/EventHandlers/RootCLPoolFactory.ts
    events:
      - event: RootPoolCreated
  - name: CLFactory
    abi_file_path: abis/CLFactory.json
    handler: src/EventHandlers/CLFactory.ts
    events:
      - event: PoolCreated
      - event: TickSpacingEnabled
  - name: CLPool
    abi_file_path: abis/CLPool.json
    handler: src/EventHandlers/CLPool.ts
    events:
      - event: Burn
      - event: Collect
      - event: CollectFees
      - event: Flash
      - event: IncreaseObservationCardinalityNext
      - event: Mint
      - event: SetFeeProtocol
      - event: Swap
  - name: NFPM
    abi_file_path: abis/NFPM.json
    handler: src/EventHandlers/NFPM/NFPM.ts
    events:
      - event: Transfer
      - event: IncreaseLiquidity
      - event: DecreaseLiquidity
  - name: VeNFT
    abi_file_path: abis/VeNFT.json
    handler: src/EventHandlers/VeNFT/VeNFT.ts
    events:
      - event: Deposit
      - event: DepositManaged
      - event: Merge
      - event: Split
      - event: WithdrawManaged
      - event: Withdraw
      - event: Transfer
  - name: Pool
    abi_file_path: abis/Pool.json
    handler: src/EventHandlers/Pool.ts
    events:
      - event: Mint
      - event: Burn
      - event: Fees
      - event: Claim
      - event: Swap
      - event: Sync
      - event: Transfer
  - name: Voter
    abi_file_path: abis/VoterV2.json
    handler: src/EventHandlers/Voter/Voter.ts
    events:
      - event: Voted
      - event: Abstained
      - event: DistributeReward
      - event: GaugeCreated
      - event: GaugeKilled
      - event: GaugeRevived
      - event: WhitelistToken
  - name: SuperchainLeafVoter
    abi_file_path: abis/SuperchainLeafVoter.json
    handler: src/EventHandlers/Voter/SuperchainLeafVoter.ts
    events:
      - event: GaugeCreated
      - event: GaugeKilled
      - event: GaugeRevived
      - event: WhitelistToken
  - name: FeesVotingReward
    abi_file_path: abis/FeesVotingReward.json
    handler: src/EventHandlers/VotingReward/FeesVotingReward.ts
    events:
      - event: ClaimRewards
  - name: BribesVotingReward
    abi_file_path: abis/BribesVotingReward.json
    handler: src/EventHandlers/VotingReward/BribesVotingReward.ts
    events:
      - event: ClaimRewards
  - name: SuperchainIncentiveVotingReward
    abi_file_path: abis/SuperchainIncentiveVotingReward.json
    handler: src/EventHandlers/VotingReward/SuperchainIncentiveVotingReward.ts
    events:
      - event: ClaimRewards
  - name: NewCLGaugeFactory
    abi_file_path: abis/NewCLGaugeFactory.json
    handler: src/EventHandlers/CLGaugeFactory/NewCLGaugeFactory.ts
    events:
      - event: SetDefaultCap
      - event: SetEmissionCap
  - name: CLGauge
    abi_file_path: abis/CLGauge.json
    handler: src/EventHandlers/Gauges/CLGauge.ts
    events:
      - event: Deposit
      - event: Withdraw
      - event: ClaimRewards
  - name: Gauge
    abi_file_path: abis/Gauge.json
    handler: src/EventHandlers/Gauges/Gauge.ts
    events:
      - event: Deposit
      - event: Withdraw
      - event: ClaimRewards
  - name: ALMDeployFactoryV2
    abi_file_path: abis/ALM/DeployFactoryV2.json
    handler: src/EventHandlers/ALM/DeployFactoryV2.ts
    events:
      - event: StrategyCreated
  - name: ALMDeployFactoryV1
    abi_file_path: abis/ALM/DeployFactoryV1.json
    handler: src/EventHandlers/ALM/DeployFactoryV1.ts
    events:
      - event: StrategyCreated
  - name: ALMCore
    abi_file_path: abis/ALM/Core.json
    handler: src/EventHandlers/ALM/Core.ts
    events:
      - event: Rebalance
  - name: ALMLPWrapperV2
    abi_file_path: abis/ALM/LPWrapperV2.json
    handler: src/EventHandlers/ALM/LPWrapperV2.ts
    events:
      - event: Deposit
      - event: Withdraw
      - event: Transfer
      - event: TotalSupplyLimitUpdated
  - name: ALMLPWrapperV1
    abi_file_path: abis/ALM/LPWrapperV1.json
    handler: src/EventHandlers/ALM/LPWrapperV1.ts
    events:
      - event: Deposit
      - event: Withdraw
      - event: Transfer
  - name: DynamicSwapFeeModule
    abi_file_path: abis/DynamicSwapFeeModule.json
    handler: src/EventHandlers/SwapFeeModule/DynamicSwapFeeModule.ts
    events:
      - event: CustomFeeSet
      - event: SecondsAgoSet
      - event: ScalingFactorSet
      - event: FeeCapSet
  - name: CustomSwapFeeModule
    abi_file_path: abis/CustomSwapFeeModule.json
    handler: src/EventHandlers/SwapFeeModule/CustomSwapFeeModule.ts
    events:
      - event: SetCustomFee
  - name: CLPoolLauncher
    handler: src/EventHandlers/PoolLauncher/CLPoolLauncher.ts
    abi_file_path: abis/CLPoolLauncher.json
    events:
      - event: Launch
      - event: Migrate
      - event: EmergingFlagged
      - event: EmergingUnflagged
      - event: PairableTokenAdded
      - event: PairableTokenRemoved
      - event: NewPoolLauncherSet
      - event: CreationTimestampSet
  - name: V2PoolLauncher
    handler: src/EventHandlers/PoolLauncher/V2PoolLauncher.ts
    abi_file_path: abis/V2PoolLauncher.json
    events:
      - event: Launch
      - event: Migrate
      - event: EmergingFlagged
      - event: EmergingUnflagged
      - event: PairableTokenAdded
      - event: PairableTokenRemoved
      - event: NewPoolLauncherSet
      - event: CreationTimestampSet
  - name: VelodromeUniversalRouter
    handler: src/EventHandlers/SuperswapsHyperlane/VelodromeUniversalRouter.ts
    abi_file_path: abis/VelodromeUniversalRouter.json
    events:
      - event: UniversalRouterBridge
      - event: CrossChainSwap
  - name: Mailbox
    handler: src/EventHandlers/SuperswapsHyperlane/Mailbox.ts
    abi_file_path: abis/Mailbox.json
    events:
      - event: DispatchId
      - event: ProcessId
chains:
  - id: 34443 # Mode
    start_block: 0
    contracts:
      - name: CustomSwapFeeModule
        address:
          - 0x479Bec910d4025b4aC440ec27aCf28eac522242B
      - name: NFPM
        address:
          - 0x991d5546C4B442B4c5fdc4c8B8b8d131DEB24702
      - name: PoolFactory
        address:
          - 0x31832f2a97Fd20664D76Cc421207669b55CE4BC0
      - name: CLFactory
        address:
          - 0x04625B046C69577EfC40e6c0Bb83CDBAfab5a55F
      - name: Pool
        address:
      - name: SuperchainLeafVoter
        address:
          - 0x97cDBCe21B6fd0585d29E539B1B99dAd328a1123
      - name: FeesVotingReward
        address:
      - name: SuperchainIncentiveVotingReward
        address:
      - name: CLPool
        address:
      - name: ALMDeployFactoryV2
        address:
          - 0xE46EC96906fc6dEC53De25F013639969Fe10180d
      - name: ALMCore
        address:
          - 0x0000000cE42D4981513060aB7E50B9e5e2D19AF1
      - name: ALMLPWrapperV2
        address:
      - name: CLGauge
        address:
      - name: Gauge
        address:
      - name: VelodromeUniversalRouter
        address:
          - 0x01D40099fCD87C018969B0e8D4aB1633Fb34763C
          - 0xa9606caaC711Ac816E568356187EC7a009500Eb2
      - name: Mailbox
        address:
          - 0x2f2aFaE1139Ce54feFC03593FeE8AB2aDF4a85A7
